//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MegaED X.rc
//
#define IDS_APP_TITLE                   102
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDI_MEGAEDX                     107
#define IDI_SMALL                       108
#define IDC_MEGAEDX                     109
#define IDD_PAL                         131
#define IDD_TILESET                     132
#define IDD_MAP                         137
#define IDD_BLOCK                       140
#define IDR_241                         141
#define IDB_TELEPORT                    142
#define IDB_XSPRITE                     143
#define IDD_SCENE                       146
#define IDB_TOOLBAR                     147
#define IDD_SETTINGS                    148
#define IDD_OFFSETS                     149
#define IDD_SPRITE                      149
#define IDB_MEGAEDXLOGO                 150
#define IDD_EVENT                       150
#define IDR_MENU1                       151
#define IDD_PROPERTY                    154
#define IDD_CHECKPOINT                  155
#define IDD_INTERNALEMULATORSETTINGS    156
#define IDD_LAYOUT                      157
#define IDD_DIALOG1                     158
#define IDD_TITLESCREEN                 159
#define IDC_PALETTEN                    1006
#define IDC_PALETTES                    1007
#define IDC_LTILEPROP                   1008
#define IDC_LTILEINDEX                  1009
#define IDC_MAPFLIP                     1013
#define IDC_MAPMIRROR                   1014
#define IDC_MAPUPLAYER                  1015
#define ID_EDITOR_BLOCKED               1022
#define ID_EDITOR_MAPED                 1023
#define ID_EDITOR_PALED                 1024
#define ID_EDITOR_SCENED                1025
#define ID_FILE_IMPORT                  1026
#define ID_FILE_OPEN                    1027
#define ID_EDITOR_TILESETED             1028
#define ID_FILE_SAVE                    1029
#define ID_FILE_SETTINGS                1030
#define ID_FILE_OFFSETS                 1031
#define ID_HELP_DONATE                  1032
#define IDM_EXIT                        1033
#define IDC_SCENED_LSCENE               1038
#define IDC_EMUPATH                     1039
#define IDC_SCENED_LSCENE2              1039
#define IDC_ERASEEMUPATH                1040
#define IDC_SCENED_LSCENE3              1040
#define IDC_SETTINGS_BROWSE             1040
#define IDC_LOADROMSTARTUP              1041
#define IDC_SCENED_LSCENE4              1041
#define IDC_SCENED_LSCENE5              1042
#define IDC_SCENED_LSCENE6              1045
#define IDC_SCENED_LSCENE7              1046
#define IDC_BLOCK_UL_S                  1047
#define IDC_SCENED_LSCENE8              1047
#define IDC_SPALETTEN                   1049
#define IDC_SPALETTES                   1050
#define IDC_SPALETTEN2                  1053
#define IDC_SPALETTES2                  1054
#define IDC_SPALETTEN3                  1055
#define IDC_EVENT_TILEBUMP              1055
#define IDC_SPALETTES3                  1056
#define IDC_EVENT_FLAG1                 1061
#define IDC_EVENT_FLAG2                 1062
#define IDC_EVENT_LOCKSUBID             1063
#define IDC_EVENT_LOCKID                1064
#define IDC_EVENT_LOCKTYPE              1065
#define IDC_EVENT_GFXREVERSE            1066
#define IDC_EVENT_ADD                   1067
#define IDC_EVENT_DELETE                1068
#define IDC_EVENT_PREV                  1069
#define IDC_EVENT_NEXT                  1070
#define IDC_EVENT_MOVE                  1071
#define IDC_EVENT_TILEBUMPNEG           1072
#define IDC_EVENT_GFXNOASSEMBLY         1073
#define IDC_REMAINING_BYTE              1074
#define IDC_REMAINING_BYTE2             1075
#define IDC_REFRESHMAIN                 1075
#define IDC_EVENT_LOCKCAMERADIR         1076
#define IDC_IEKEYUP                     1076
#define IDC_IEKEYDOWN                   1077
#define IDC_IEKEYLEFT                   1078
#define IDC_IEKEYRIGHT                  1079
#define IDC_IESAVE                      1080
#define IDC_IEJOYNUM                    1081
#define IDC_LREFRESHMAIN                1084
#define IDC_CHECKPOINT_OFFSET_NAME      1085
#define IDC_ENEMYNAME                   1087
#define IDC_IEKEYA                      1088
#define IDC_IEKEYB                      1089
#define IDC_IEKEYX                      1090
#define IDC_IEKEYY                      1091
#define IDC_IEKEYL                      1096
#define IDC_IEKEYR                      1097
#define IDC_IEKEYSELECT                 1098
#define IDC_IEKEYSTART                  1099
#define IDC_IEKEYNEXTSTATE              1100
#define IDC_IEKEYPREVSTATE              1101
#define IDC_IEKEYSAVESTATE              1102
#define IDC_IEKEYLOADSTATE              1103
#define IDC_IEKEYFASTFORWARD            1104
#define IDC_IECANCEL                    1112
#define ID_IMPORT_FROMASNESGAME         32824
#define ID_IMPORT_FROMAGENESISGAME      32825
#define ID_IMPORT_FROMAGBAGAME          32826
#define ID_IMPORT_SNES                  32827
#define ID_IMPORT_GEN                   32828
#define ID_IMPORT_GBA                   32829
#define ID_FILE_SAVEAS                  32830
#define ID_EDITOR_SPRITEEDITOR          32831
#define ID_EDITOR_SPRITED               32832
#define ID_EDITOR_EVENTEDITOR           32833
#define ID_EDITOR_EVENTED               32834
#define ID_EDITOR_PROPERTYEDITOR        32835
#define ID_EDITOR_PROPERTYED            32836
#define ID_EDITOR_CHECKPOINTEDITOR      32837
#define ID_EDITOR_CHECKPOINTED          32838
#define ID_FILE_RUNINTERNALEMULATOR     32839
#define ID_Menu                         32840
#define ID_FILE_INTERNALEMULATORSETTINGS 32841
#define ID_EDITOR_LAYOUTEDITOR          32842
#define ID_EDITOR_LAYOUTD               32843
#define ID_FILE_EXPANDROM               32844
#define ID_EMULATOR_ENDEMULATION        32845
#define ID_EDITOR_TITLESCREEN           32846
#define ID_EDITOR_UNDO                  32847
#define IDC_LMAPINDEX                   0x9000
#define IDC_LMAPTILEINDEX               36865
#define IDC_LBLOCKINDEX                 0x9200
#define IDC_LBLOCKMAPINDEX              37377
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32848
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
